services:
  postgres:
    image: postgres:17
    container_name: gastro-postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gastro_atlas

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/internal/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  postgres_data: