// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    ingredient_id,
    title,
    description,
    time_period,
    entity,
    location,
    sources,
    confidence
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, ingredient_id, title, description, time_period, entity, location, sources, confidence
`

type CreateEventParams struct {
	IngredientID int32    `json:"ingredientId"`
	Title        string   `json:"title"`
	Description  string   `json:"description"`
	TimePeriod   string   `json:"timePeriod"`
	Entity       string   `json:"entity"`
	Location     string   `json:"location"`
	Sources      []string `json:"sources"`
	Confidence   string   `json:"confidence"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.IngredientID,
		arg.Title,
		arg.Description,
		arg.TimePeriod,
		arg.Entity,
		arg.Location,
		arg.Sources,
		arg.Confidence,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.Title,
		&i.Description,
		&i.TimePeriod,
		&i.Entity,
		&i.Location,
		&i.Sources,
		&i.Confidence,
	)
	return i, err
}

const getEventsByIngredient = `-- name: GetEventsByIngredient :many
SELECT id, ingredient_id, title, description, time_period, entity, location, sources, confidence
FROM events
WHERE ingredient_id = $1
ORDER BY id
`

func (q *Queries) GetEventsByIngredient(ctx context.Context, ingredientID int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByIngredient, ingredientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.Title,
			&i.Description,
			&i.TimePeriod,
			&i.Entity,
			&i.Location,
			&i.Sources,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
