// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    ingredient_id,
    description,
    time_period,
    location,
    start_year,
    end_year,
    latitude,
    longitude
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, ingredient_id, description, time_period, location, start_year, end_year, latitude, longitude
`

type CreateEventParams struct {
	IngredientID int32         `json:"ingredientId"`
	Description  string        `json:"description"`
	TimePeriod   string        `json:"timePeriod"`
	Location     string        `json:"location"`
	StartYear    pgtype.Int4   `json:"startYear"`
	EndYear      pgtype.Int4   `json:"endYear"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.IngredientID,
		arg.Description,
		arg.TimePeriod,
		arg.Location,
		arg.StartYear,
		arg.EndYear,
		arg.Latitude,
		arg.Longitude,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.Description,
		&i.TimePeriod,
		&i.Location,
		&i.StartYear,
		&i.EndYear,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getEventsByIngredient = `-- name: GetEventsByIngredient :many
SELECT id, ingredient_id, description, time_period, location, start_year, end_year, latitude, longitude
FROM events
WHERE ingredient_id = $1
ORDER BY id
`

func (q *Queries) GetEventsByIngredient(ctx context.Context, ingredientID int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByIngredient, ingredientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.Description,
			&i.TimePeriod,
			&i.Location,
			&i.StartYear,
			&i.EndYear,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
