// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingredients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIngredientBySlug = `-- name: GetIngredientBySlug :one
SELECT
    id,
    name,
    slug,
    description
FROM ingredients
WHERE slug = $1
`

func (q *Queries) GetIngredientBySlug(ctx context.Context, slug string) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientBySlug, slug)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
	)
	return i, err
}

const getIngredients = `-- name: GetIngredients :many
SELECT
    id,
    name,
    slug,
    description
FROM ingredients
ORDER BY name
`

func (q *Queries) GetIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, getIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIngredient = `-- name: UpsertIngredient :one
INSERT INTO ingredients (
    name,
    slug,
    description
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (slug)
DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description
RETURNING id
`

type UpsertIngredientParams struct {
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpsertIngredient(ctx context.Context, arg UpsertIngredientParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertIngredient, arg.Name, arg.Slug, arg.Description)
	var id int32
	err := row.Scan(&id)
	return id, err
}
