// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingredients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (
    name,
    slug,
    description
)
VALUES (
    $1,
    $2,
    $3
)

RETURNING
    id,
    name,
    slug,
    description
`

type CreateIngredientParams struct {
	Name        string
	Slug        string
	Description pgtype.Text
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient, arg.Name, arg.Slug, arg.Description)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
	)
	return i, err
}

const getIngredientBySlug = `-- name: GetIngredientBySlug :one
SELECT
    id,
    name,
    slug,
    description
FROM ingredients
WHERE slug = $1
`

func (q *Queries) GetIngredientBySlug(ctx context.Context, slug string) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientBySlug, slug)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
	)
	return i, err
}

const getIngredients = `-- name: GetIngredients :many
SELECT
    id,
    name,
    slug,
    description
FROM ingredients
ORDER BY name
`

func (q *Queries) GetIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, getIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
