// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingredient_places.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIngredientPlaces = `-- name: GetIngredientPlaces :many
SELECT
    p.id,
    p.name,
    p.type,
    p.latitude,
    p.longitude,
    ip.relationship,
    ip.start_year,
    ip.end_year,
    ip.notes
FROM ingredient_places ip
JOIN places p ON p.id = ip.place_id
WHERE ip.ingredient_id = $1
ORDER BY ip.start_year
`

type GetIngredientPlacesRow struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	Type         string      `json:"type"`
	Latitude     float64     `json:"latitude"`
	Longitude    float64     `json:"longitude"`
	Relationship string      `json:"relationship"`
	StartYear    pgtype.Int4 `json:"startYear"`
	EndYear      pgtype.Int4 `json:"endYear"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) GetIngredientPlaces(ctx context.Context, ingredientID int32) ([]GetIngredientPlacesRow, error) {
	rows, err := q.db.Query(ctx, getIngredientPlaces, ingredientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIngredientPlacesRow
	for rows.Next() {
		var i GetIngredientPlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Latitude,
			&i.Longitude,
			&i.Relationship,
			&i.StartYear,
			&i.EndYear,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIngredientPlace = `-- name: UpsertIngredientPlace :exec
INSERT INTO ingredient_places (
    ingredient_id,
    place_id,
    relationship,
    start_year,
    end_year,
    notes
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (ingredient_id, place_id)
DO UPDATE SET
    relationship = EXCLUDED.relationship,
    start_year = EXCLUDED.start_year,
    end_year = EXCLUDED.end_year,
    notes = EXCLUDED.notes
`

type UpsertIngredientPlaceParams struct {
	IngredientID int32       `json:"ingredientId"`
	PlaceID      int32       `json:"placeId"`
	Relationship string      `json:"relationship"`
	StartYear    pgtype.Int4 `json:"startYear"`
	EndYear      pgtype.Int4 `json:"endYear"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) UpsertIngredientPlace(ctx context.Context, arg UpsertIngredientPlaceParams) error {
	_, err := q.db.Exec(ctx, upsertIngredientPlace,
		arg.IngredientID,
		arg.PlaceID,
		arg.Relationship,
		arg.StartYear,
		arg.EndYear,
		arg.Notes,
	)
	return err
}
