// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ingredient struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
}

type IngredientPlace struct {
	IngredientID int32       `json:"ingredientId"`
	PlaceID      int32       `json:"placeId"`
	Relationship string      `json:"relationship"`
	StartYear    pgtype.Int4 `json:"startYear"`
	EndYear      pgtype.Int4 `json:"endYear"`
	Notes        pgtype.Text `json:"notes"`
}

type Place struct {
	ID        int32   `json:"id"`
	Name      string  `json:"name"`
	Type      string  `json:"type"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}
