// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID           int32         `json:"id"`
	IngredientID int32         `json:"ingredientId"`
	Description  string        `json:"description"`
	TimePeriod   string        `json:"timePeriod"`
	Location     string        `json:"location"`
	StartYear    pgtype.Int4   `json:"startYear"`
	EndYear      pgtype.Int4   `json:"endYear"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
}

type Ingredient struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
}
