// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: places.sql

package sqlc

import (
	"context"
)

const upsertPlace = `-- name: UpsertPlace :one
INSERT INTO places (
    name,
    type,
    latitude,
    longitude
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (name)
DO UPDATE SET
    type = EXCLUDED.type,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude
RETURNING id
`

type UpsertPlaceParams struct {
	Name      string  `json:"name"`
	Type      string  `json:"type"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

func (q *Queries) UpsertPlace(ctx context.Context, arg UpsertPlaceParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertPlace,
		arg.Name,
		arg.Type,
		arg.Latitude,
		arg.Longitude,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
